# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WrapperOld' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WrapperOld
#  pod "Nami", "1.5.0"
  # pod "Nami", "2.5.3"

end
